# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=postgres
export POSTGRES_PASSWORD=myPassword
export POSTGRES_HOST=mydbinstance.csxbuclmtj3c.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=arn:aws:s3:::myawsbucket-75139724085
export AWS_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=mysecretstring
export URL=http://localhost:8100
eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
POSTGRES_HOST=$POSTGRES_HOST
AWS_REGION=$AWS_REGION
AWS_PROFILE=$AWS_PROFILE
AWS_BUCKET=$AWS_BUCKET
URL=$URL
JWT_SECRET=$JWT_SECRET
DB_HOST=DB_HOST=$DB_HOST
DB_USER=$DB_USER
RDS_DIALECT=$RDS_DIALECT
DB_PASSWORD=$DB_PASSWORD
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME=
ENV=$ENV
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY